#!/usr/bin/env bash

export CONTECO_LABEL="external.ksql_cli - ContEco"
export CONTECO_DESCRIPTION="Confluent KSQLB CLI image with ContEco external prerequisites installed."

export CONTECO_TYPE="external"
export CONTECO_NAME="ksql_cli"
export CONTECO_TAG="5.4.0"

export CONTECO_BASE="confluentinc/cp-ksql_cli:5.4.0"
export CONTECO_BUILD="external-mapped"
